
server:
  port: 8081

spring:
  application:
          name: gateway-server

eureka:
  instance:
    hostname: localhost
    metadata-map:
      zone: china
      instanceId: ${spring.application.name}:${random.value}
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



